decharla2023/decharla/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('configuracion', views.configuracion),
    path('ayuda', views.ayuda),
    path('<str:sala>', views.get_sala, name='get_sala'),
    path('<str:sala>/json', views.get_sala),
    path('<str:sala>/xml', views.get_sala, name='xml'),
    path('<str:sala>/dinamic', views.get_sala),
]

decharla2023/decharla2023/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('decharla.urls')),
    path('admin/', admin.site.urls),
]

decharla2023/decharla/models.py
from django.db import models


class Sala(models.Model):
    def __str__(self):
        return self.nombre
    nombre = models.CharField(max_length=64)
    unread = models.IntegerField(default=0)


class Mensaje(models.Model):
    def __str__(self):
        return str(self.id) + " : " + self.sala.nombre + " : " + self.text
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    author = models.CharField(max_length=64)
    text = models.TextField()
    isimg = models.BooleanField()
    date = models.DateTimeField()


class Contraseña(models.Model):
    def __str__(self):
        return self.contraseña
    contraseña = models.CharField(max_length=64)


class Voto(models.Model):
    mensaje = models.ForeignKey(Mensaje, on_delete=models.CASCADE)
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)

decharla2023/decharla/forms.py
from django import forms
from .models import Sala, Mensaje


class SalaForm(forms.ModelForm):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombre de la sala'}), label='')
    class Meta:
        model = Sala
        fields = ['nombre']


class MensajeForm(forms.ModelForm):
    mensaje = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Escribe tu mensaje'}), label='')
    class Meta:
        model = Mensaje
        fields = ['mensaje']

decharla2023/decharla/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Sala, Mensaje, Contraseña, Voto
from .forms import SalaForm, MensajeForm
from django.views.decorators.csrf import csrf_exempt
import fnmatch
import xml.etree.ElementTree as ET
from .serializers import MySerialiser
from collections import Counter
import json
import random
import string

# diccionario con clave id del mensaje y valor una lista de sessionid que han votado en él
# p.ej {78: ['eqmnyedyx52vvuliugm71dxfsypr9c83']}
users_vote = {}
# diccionario con clave sessionid del usuario y valor una lista de ids de los mensajes leidos
# p.ej {'eqmnyedyx52vvuliugm71dxfsypr9c83': [72, 73, 74, 75, 77, 78]}
users_read = {}


# Cuando cierra la sesion, todos los mensajes pasan a estar no leidos
# y las cookies de configuracion y autenticacion se borran
def close_session(request, response):
    global users_read
    session = request.COOKIES["sessionid"]
    if session in users_read:
        del users_read[session]

    response.delete_cookie("IS_AUTH")
    if request.COOKIES.get('FONT_TYPE', 'NOT_SET') != 'NOT_SET':
        response.delete_cookie("FONT_TYPE")
    if request.COOKIES.get('FONT_SIZE', 'NOT_SET') != 'NOT_SET':
        response.delete_cookie("FONT_SIZE")
    if request.COOKIES.get('CHARLADOR', 'Anónimo') != 'Anónimo':
        response.set_cookie('CHARLADOR', 'Anónimo')
    return response


# En Chrome no está la cookie sessionid como sí está en Firefox. Es necesaria
def check_sessionid(request):
    n = 32  # Longitud de la cookie de session
    if request.COOKIES.get('sessionid', 'NOT_SET') == "NOT_SET":
        # Es criptográficamente segura
        cookie = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.ascii_lowercase + string.digits)
                         for _ in range(n))
    else:
        # Ya está puesta en el navegador
        cookie = False
    return cookie


# Marca como leidos los mensajes de una sala cuando el usuario entra en ella
def mark_as_read(request, sala):
    global users_read
    session_id = request.COOKIES["sessionid"]
    s = Sala.objects.get(nombre=sala)
    msgs = Mensaje.objects.filter(sala=s)
    sala_msgs = []
    for m in msgs:
        sala_msgs.append(m.id)
    users_read[session_id] = users_read.get(session_id, []) + sala_msgs


# Comprueba que mensajes ha leido el usuario y rellena el campo unread en la sala para mostrarlo en la pagina principal
def set_unread_messages(request):
    global users_read
    salas = Sala.objects.all()
    session_id = request.COOKIES["sessionid"]
    unread_messages = {}

    if session_id in users_read:
        read_msgs = users_read[session_id]
        for s in salas:
            sa = Sala.objects.get(nombre=s.nombre)
            msgs = Mensaje.objects.filter(sala=sa)
            for m in msgs:
                if m.id not in read_msgs:
                    unread_messages[m.id] = m.sala.nombre
    else:
        # si el sessionid no esta en el users_read es que no ha leido nada porque no se ha metido en ninguna sala
        for s in salas:
            sa = Sala.objects.get(nombre=s.nombre)
            msgs = Mensaje.objects.filter(sala=sa)
            for m in msgs:
                unread_messages[m.id] = m.sala.nombre

    aux = Counter(unread_messages.values())

    for s in salas:
        sa = Sala.objects.get(nombre=s.nombre)
        sa.unread = aux[s.nombre]
        sa.save()


# Revisa la base de datos y limpia los datos para mostrarlos en el pie del sitio
def pie_stats(contexto):
    salas_activas = []
    mensajes_texto = 0
    mensajes_imagenes = 0
    salas = Sala.objects.all()

    for s in salas:
        sa = Sala.objects.get(nombre=s.nombre)
        msgs = Mensaje.objects.filter(sala=sa)
        for m in msgs:
            if s.nombre not in salas_activas:
                salas_activas.append(s.nombre)
            if m.isimg:
                mensajes_imagenes = mensajes_imagenes + 1
            else:
                mensajes_texto = mensajes_texto + 1

    contexto["salas_activas"] = salas_activas.__len__()
    contexto["mensajes_texto"] = mensajes_texto
    contexto["mensajes_imagenes"] = mensajes_imagenes
    return contexto


# Comprueba si los mensajes deben mostrarse en formato normal, JSON o dinámico
def check_format(url, contexto, method, sala):
    updated_contexto = contexto
    if method == "POST":
        updated_contexto['json'] = False
        if fnmatch.fnmatch(url, '*/json'):
            updated_contexto['json'] = True
        elif fnmatch.fnmatch(url, '*/dinamic'):
            updated_contexto['dinamic'] = True
        else:
            updated_contexto['regular'] = True
    elif method == "GET":
        if fnmatch.fnmatch(url, '*/json'):
            updated_contexto['json'] = True
            updated_contexto['objects'] = get_json_msgs(sala)
        elif fnmatch.fnmatch(url, '*/dinamic'):
            updated_contexto['dinamic'] = True
            json_msgs=get_json_msgs(sala)
            update_json_file(json_msgs)
        else:
            updated_contexto["regular"] = True
    return updated_contexto


# Comprueba si la sala existe, y si no la crea
def check_sala(sala):
    try:
        s = Sala.objects.get(nombre=sala)
    except Sala.DoesNotExist:
        s = Sala(nombre=sala)
        s.save()


# Busca en las cookies de la peticion para saber si hay parametros de configuracion
def search_conf(request, contexto):
    if request.COOKIES.get('FONT_TYPE', 'UNDEFINED') != "UNDEFINED":
        type = request.COOKIES['FONT_TYPE']
        contexto["FONT_TYPE"] = type

    if request.COOKIES.get('FONT_SIZE', 'UNDEFINED') != "UNDEFINED":
        size = request.COOKIES['FONT_SIZE']
        contexto["FONT_SIZE"] = size

    nombre = request.COOKIES.get('CHARLADOR', 'Anónimo')
    contexto["CHARLADOR"] = nombre
    return contexto


# Reescribe el archivo json
def update_json_file(json_msgs):
    location = r"/home/paula/ST/ST-src/decharla2023/decharla/static/json/messages.json"
    with open(location, "w") as output:
        json.dump(json_msgs, output)


# Devuelve los mensajes de la sala en formato JSON
def get_json_msgs(sala):
    s = MySerialiser()
    msgs = Mensaje.objects.filter(sala=Sala.objects.get(nombre=sala).id)
    serialized = s.serialize(msgs)
    json_msgs = json.dumps(serialized, indent=4, default=str)
    return json_msgs


# Actualiza los votos
def update_voto(voto, upvotes, downvotes):
    voto.upvote = upvotes
    voto.downvote = downvotes
    voto.save()


# Revisa si el sessionid de la peticion ya ha votado ya en ese mensaje o no. Si no ha votado cuenta el voto, pero
# si intenta votar dos veces en el mismo mensaje recibe un warning.
def check_if_voted(request, contexto):
    global users_vote
    m = Mensaje.objects.get(id=request.POST["mensaje_id"])
    session_id = request.COOKIES["sessionid"]

    v = Voto.objects.get(mensaje=m)
    upvotes = Voto.objects.get(mensaje=m).upvote
    downvotes = Voto.objects.get(mensaje=m).downvote

    if m.id in users_vote.keys():
        if session_id in users_vote[m.id]:
            contexto["already_voted"] = True
    else:
        users_vote[m.id] = [session_id]
        if request.POST["action"] == "Upvote":
            upvotes = upvotes + 1
        if request.POST["action"] == "Downvote":
            downvotes = downvotes + 1
        update_voto(v, upvotes, downvotes)
    return contexto


# Publica un mensaje en una sala y crea la votacion
def publish_msg(img, msg, sala, charlador):
    fecha = timezone.now()
    m = Mensaje(sala=sala, text=msg, author=charlador, date=fecha, isimg=img)
    m.save()
    v = Voto(mensaje=m, upvote=0, downvote=0)
    v.save()


# Publica los mensajes recibidos en XML, comprobando la autenticación
def handle_xml(request, sala, contexto):
    xmldoc = request.body.decode()
    root = ET.fromstring(xmldoc)
    auth = False
    if request.COOKIES.get("IS_AUTH") == "TRUE":
        for m in root.iter('message'):
            check_sala(sala)
            publish_msg(m.attrib['isimg'], m.find('text').text, Sala.objects.get(nombre=sala), contexto["CHARLADOR"])

    else:
        if root.tag == "Authorization":
            try:
                c = Contraseña.objects.get(contraseña="".join(root.attrib.values()))
                sa = Sala.objects.get(nombre=sala)
                contexto["sala"] = sala
                contexto["regular"] = True
                response = render(request, 'decharla/sala.html', contexto)
                response.set_cookie("IS_AUTH", "TRUE")
                auth = True
                for m in root.iter('message'):
                    check_sala(sala)
                    publish_msg(m.attrib['isimg'], m.find('text').text, sa, contexto["CHARLADOR"])
            except Contraseña.DoesNotExist:
                pass
    return auth

# Sirve las salas
@csrf_exempt
def get_sala(request, sala):
    absolute_url = request.build_absolute_uri()
    salas = Sala.objects.all()
    formulario_mensaje = MensajeForm()
    formulario_sala = SalaForm()
    contexto = {'msg_form': formulario_mensaje, 'sala_form': formulario_sala, 'salas': salas}
    bad_passwd = ""
    contexto = search_conf(request, contexto)
    contexto = pie_stats(contexto)
    xml_auth = False

    if request.method == "PUT":
        if fnmatch.fnmatch(absolute_url, '*/xml'):
            xml_auth = handle_xml(request, sala, contexto)
            new_msgs = get_json_msgs(sala)
            update_json_file(new_msgs)

    if request.method == "POST":
        contexto = check_format(absolute_url, contexto, "POST", sala)
        if request.POST["action"] == "Accede":
            check_sala(sala)
            formulario = SalaForm(request.POST)
            if formulario.is_valid():
                sala = formulario.cleaned_data['nombre']
                return redirect('get_sala', sala=sala)

        if request.POST["action"] == "Cierra":
            response = render(request, 'decharla/sala.html', contexto)

decharla2023/decharla/templates/decharla/ayuda.html
{% extends 'decharla/schema.html' %}

{% block cuerpo %}
    <div id="page_title">
        <h3>Ayuda</h3>
    </div>
    Proyecto realizado por Paula Gallego Vieira (Grado en Ingeniería Telemática) para la asignatura Servicios Telemáticos.<br>
    La aplicación web <i>DeCharla</i> alberga diversas salas de chat en las cuales los usuarios pueden publicar mensajes de texto o imagen.
    Adicionalmente, los usuarios pueden votar una única vez en cada uno de los mensajes.<br>
    La paleta de colores del sitio ha sido generada usando el algoritmo de aprendizaje máquina de <a href="https://huemint.com/website-1/">Huemint</a>
    y el logotipo y favicon han sido creados en <a href="https://www.canva.com/">Canva</a>.
    Los iconos del sitio son del paquete <a href="https://icon-icons.com/es/pack/Essential-Pack-01/3436"><i>Essential Pack 01</i></a> por Subash Matheswaran
{% endblock %}

decharla2023/decharla/templates/decharla/configuracion.html
{% extends 'decharla/schema.html' %}

{% block cuerpo %}
    <style>
        .test1 {
            font-family: "Times New Roman", Times, serif;
        }
        .test2 {
            font-family: Arial, sans-serif;
        }
        .test3 {
            font-family: "Lucida Console", monospace;
        }
    </style>
    <h3 id="page_title">Configuración</h3>
    <form method="POST">
    {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Introduce tu nombre de charlador</label>
            <input type="nombre" name="nombre" class="form-control" id="exampleFormControlInput1" placeholder="Por defecto charlas como 'Anónimo'">
        </div>
        {% csrf_token %}
        <button class="btn btn-outline-light" type="submit" name="action" value="Enviar nombre">Enviar nombre</button>
    </form>

    <br>
    El sitio está disponible en las siguientes tipografías:
    <div class="container border">
        <div class="row border" id="conf_tables">
            <div class="col-4 border"><p style="text-align:center" class="test1">Times New Roman</p></div>
            <div class="col-4 border"><p style="text-align:center" class="test2">Arial</p></div>
            <div class="col-4 border"><p style="text-align:center" class="test3">Lucida Console</p></div>
        </div>
    </div>
    Y en los siguientes tamaños de letra:
        <div class="container border">
        <div class="row border" id="conf_tables">
            <div class="col-4 border"><p style="text-align:center; font-size: smaller">Pequeño</p></div>
            <div class="col-4 border"><p style="text-align:center;font-size: medium">Mediano</p></div>
            <div class="col-4 border"><p style="text-align:center;font-size: larger">Grande</p></div>
        </div>
    </div>
    <br>
    <form method="POST">
    {% csrf_token %}
        <div class="form-group">
            <select name="tipo" id="tipo" class="form-control" required>
                <option value="">Elige un tipo de letra</option>
                <option value="Times">Times New Roman (Serif)</option>
                <option value="Arial">Arial (Sans-serif)</option>
                <option value="Lucida">Lucida Console (Monospace)</option>
            </select>
        </div>

        <div class="form-group">
            <select name="tamaño" id="tamaño" class="form-control" required>
                <option value="">Elige un tamaño de letra</option>
                <option value="smaller">Pequeño</option>
                <option value="medium">Mediano</option>
                <option value="larger">Grande</option>
            </select>
        </div>

        {% csrf_token %}
        <button type="submit" class="btn btn-outline-light" name="action" value="Enviar conf">Enviar configuración</button>
    </form>
{% endblock %}

decharla2023/decharla/templates/decharla/login.html
{% extends 'decharla/schema.html' %}

{% block cuerpo %}
{% if BadPasswd == True%}
<div class="alert alert-danger" role="alert">
    ¡Has introducido una contraseña incorrecta! Inténtalo de nuevo
</div>
{% endif %}
<div class="alert alert-warning" role="alert">
    ADVERTENCIA: Debes autenticarte para navegar en este sitio
</div>
<form class="form-inline" method="POST">
  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Contraseña</label>
    <input type="password" name = "contraseña" class="form-control" placeholder="Contraseña">
  </div>
  {% csrf_token %}
  <button type="submit" class="btn btn-primary mb-2" name="action" value="Autentica">Autenticate</button>
</form>
{% endblock %}

decharla2023/decharla/templates/decharla/sala.html
{% extends 'decharla/schema.html' %}
<head>
{% load static %}
<link href="{% static "css/style.css" %}" rel="stylesheet">

</head>

{% block cuerpo %}
    <div id="page_title">
        <h3>{{ sala.nombre }}</h3>
    </div>
    <br>

    <div id="msgform">
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
                {{ msg_form.as_p }}
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="checkbox" id="isimg" name="isimg" value="True" />
                    <label for="IsImage"><img src="{%static "imagen.png" %}">¿Es una imagen?</label>
                </div>
                <div class="col">
                    <button class="btn btn-outline-light" type="submit" name="action" value="Publica">Publicar mensaje</button>
                </div>
            </div>
        </form>
    </div>

    {% if dinamic == True%}
        <div id="messages"></div>
        <script>
            const url_messages = '{% static "json/messages.json" %}';
        </script>
        <script type="text/javascript" src="{% static "js/dinamic.js" %}"></script>
    {% endif %}

    {% if json == True%}
        <pre>{{ objects }}</pre>
    {% endif %}

    {% if regular == True%}
        <br>

        {% if already_voted == True%}
            <div class="alert alert-info" role="alert">
                INFO: No puedes votar dos veces en el mismo mensaje
            </div>
        {% endif %}

        {% for m in sala.mensaje_set.all reversed %}
                <div id="msg_div">
                    <div id="msg_header">
                        <img id="msg_autor" src="{%static "admin.png" %}">
                        <b> {{ m.author }} </b><br>
                        <b> ({{ m.date }}) </b><br>
                    </div>
                    <div id="msg_body">
                        {% if m.isimg == True%}
                            <img src="{{ m.text }}" id="msg_img">
                        {% else %}
                            {{ m.text }} <br>
                        {% endif %}
                        <form method="POST">
                            <input hidden="hidden" name="mensaje_id" value="{{ m.id }}">
                            <div style="display:flex; justify-content:flex-end; width:100%; padding:0;">
                                <button class="btn btn-outline-light btn-sm" type="submit" name="action" value="Upvote">
                                    <img src="{%static "up.png" %}"> {% with m.voto_set.all|first as v %}{{ v.upvote }}{% endwith %}

                                </button>
                                <button class="btn btn-outline-light btn-sm" type="submit" name="action" value="Downvote">
                                    <img src="{%static "down.png" %}"> {% with m.voto_set.all|first as v %}{{ v.downvote }}{% endwith %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                <br>
        {% empty %}
            <p>Lo sentimos, no hay mensajes en esta sala.</p>
        {% endfor %}
    {% endif %}
{% endblock %}

decharla2023/decharla/templates/decharla/schema.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DeCharla2023</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static "favicon.ico" %}">
</head>
<body>
<style>
    body{
        {% if FONT_TYPE == "Times"%}
            font-family: 'Times New Roman', serif;
        {% elif FONT_TYPE == "Lucida"%}
            font-family: "Lucida Console", monospace;
        {% elif FONT_TYPE == "Arial"%}
            font-family: Arial, sans-serif;
        {% endif %}

        {% if FONT_SIZE == "smaller"%}
            font-size: smaller;
        {% elif FONT_SIZE == "medium"%}
            font-size: medium;
        {% elif FONT_SIZE == "larger"%}
            font-size: larger;
        {% endif %}
    }
</style>

<div class="container border">
            {% block cabecera %}
                <div class="row" id="site_title">
                {% load static %}
                <a id="logo" href="/"><img src="{%static "logo.png" %}" alt="Logo del sitio" height="200px" width="300px"/></a>
                </div>
            {% endblock %}

            {% block menu %}
                <ul class="nav nav-pills justify-content-center nav-justified">
                    <li class="nav-item">
                        <a class="nav-link active" id="nav_pill" href="/">Principal<img src="{%static "principal.png" %}"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" id="nav_pill" href="configuracion">Configuración<img src="{%static "configuracion.png" %}"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" id="nav_pill" href="ayuda">Ayuda<img src="{%static "ayuda.png" %}"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" id="nav_pill" href="admin/">Admin<img src="{%static "admin.png" %}"></a>
                    </li>
                </ul>

                <br>
            {% endblock %}

    <div class="row">
        <div class="col">
            {% block cuerpo %}
                <p>aqui va el cuerpo</p>
            {% endblock %}
            {% block pie %}
                <div id="pie">
                Mensajes: {{ mensajes_texto }} (textuales), {{ mensajes_imagenes }} (imágenes).<br>Salas activas: {{ salas_activas }}
                </div>
            {% endblock %}
        </div>
        <div class="col-sm-4 text-left">
            {% block extra %}
                <div id="extra">
                    <img src="{%static "charlador.png" %}">Charlador: {{ CHARLADOR }}
                <br><br>
                {% if sesion_abierta == True%}
                <form method="POST">
                    <input hidden="hidden" name="" value="">
                    {% csrf_token %}
                    <button class="btn btn-outline-dark btn-block" type="submit" name="action" value="Cierra">Cierra tu sesión</button>
                </form>
                {% endif %}
                <br>
                Busca o crea una sala:
                <form method="POST">
                    {{ sala_form.as_div }}
                    {% csrf_token %}
                    <br>
                    <button class="btn btn-outline-light btn-block" type="submit" name="action" value="Accede">Accede</button>
                </form>
                </div>
            {% endblock %}
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>